# Generated by Django 5.2.7 on 2025-10-23 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceIoT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(choices=[('ESP32', 'ESP32'), ('ESP32-S2', 'ESP32-S2'), ('ESP32-S3', 'ESP32-S3'), ('ARDUINO_UNO', 'Arduino Uno'), ('ARDUINO_MEGA', 'Arduino Mega'), ('STM32F407', 'STM32F407'), ('DESCONOCIDO', 'Desconocido')], default='DESCONOCIDO', max_length=20, verbose_name='Modelo del Dispositivo')),
                ('device_id', models.CharField(max_length=100, unique=True, verbose_name='ID del Dispositivo')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True, verbose_name='Última Conexión')),
                ('en_linea', models.BooleanField(default=False, verbose_name='En Línea')),
                ('topicos_pub', models.JSONField(default=list, verbose_name='Tópicos de Publicación (Pub)')),
                ('topicos_sub', models.JSONField(default=list, verbose_name='Tópicos de Suscripción (Sub)')),
            ],
            options={
                'verbose_name': 'Dispositivo IoT',
                'verbose_name_plural': 'Dispositivos IoT',
            },
        ),
    ]
